name: Push

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-dockerfile:
    name: Build dockerfile
    runs-on: ubuntu-latest
    container:
      image: quay.io/podman/stable:v5.5.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build image
        run: |
          podman build .